# Generated by Django 4.2.8 on 2024-01-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passby',
            field=models.CharField(max_length=20),
        ),
    ]
